site_name: Planificación y administración de redes
site_url: https://joperpu.github.io/par2425
theme:
  name: material
  language: es
  favicon: assets/images/logo.ico
  features:
    - content.code.copy
  palette: 
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "assets/images/logo.png"
nav:
  - Página principal: index.md
  - UD1 - Introducción a las redes de comunicaciones:
    - Teoría UD1: ud1.md
    - Práctica 1.1: pr1.1.md
    - Práctica 1.2: pr1.2.md
    - Práctica 1.3: pr1.3.md
    - Práctica 1.4: pr1.4.md
    - Práctica 1.5: pr1.5.md
  - UD2 - Integración de elementos de una red:
    - Teoría UD2: ud2.md
    - Práctica 2.1: pr2.1.md
    - Práctica 2.2: pr2.2.md
    - Práctica 2.3: pr2.3.md

copyright: "2024 José María Pérez Puentes - Licencia CC BY-NC-SA 4.0"

extra:
  generator: true

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences